function buildHomeScreenModel({
  auth,
  ownedRooms,
  upcomingOpenParties,
  topRatedRooms,
  commands,
  ui,
}) {
  return {
    creatingRoom: ui.creatingRoom,
    user: auth.user,
    ownedRooms,
    upcomingOpenParties,
    topRatedRooms,
    onCreateRoom: commands.handleCreateRoom,
    onCreatePartyRoom: commands.handleCreatePartyRoom,
    onDeleteRoom: commands.handleDeleteRoom,
    onJoinRoom: commands.handleJoinRoom,
    onSeedRooms: commands.handleSeedRooms,
    onSignIn: auth.signInWithGoogle,
    onSignOut: auth.signOutUser,
    onUpdateDisplayName: auth.updateDisplayName,
    onCreateRoomFromYt: commands.handleCreateRoomFromYt,
    onAddYtToRoom: commands.handleAddYtToRoom,
    onCopyForeignRoom: (sourceRoom) => commands.handleCreateRoomFromYt(sourceRoom.name || 'Kopia', sourceRoom.songs ?? []),
    onAppendForeignToRoom: commands.handleAddYtToRoom,
    onSubmitMessage: commands.submitContactMessage,
  }
}

function buildHeaderModel({
  auth,
  ownedRooms,
  room,
  showOwnerUI,
  leftPanel,
  toggleLeftPanel,
  shareLinks,
  copied,
  suggestions,
  commands,
}) {
  return {
    showOwnerUI,
    leftPanel,
    toggleLeftPanel,
    user: auth.user,
    signInWithGoogle: auth.signInWithGoogle,
    signOutUser: auth.signOutUser,
    updateDisplayName: auth.updateDisplayName,
    onCreateRoomFromYt: commands.handleCreateRoomFromYt,
    onAddYtToRoom: commands.handleAddYtToRoom,
    currentRoomId: auth.roomId,
    ownedRooms,
    onShareGuestLink: shareLinks.copyVoterLink,
    guestCopied: copied === 'voter',
    proposalsCount: Object.keys(room?.votingProposals ?? {}).length + (suggestions?.length ?? 0),
  }
}

function buildOwnerSidebarModel({
  room,
  canEditRoom,
  settings,
  suggestions,
  ownedRooms,
  ui,
  playbackState,
  commands,
  playlistActions,
  songActions,
  viewMode,
  shareLinks,
}) {
  return {
    ui: {
      leftPanel: ui.leftPanel,
    },
    songsPanel: {
      room,
      isPlaying: playbackState.isPlaying,
      currentSong: playbackState.currentSong,
      playSongNow: viewMode.playSongNow,
      deleteSong: songActions.deleteSong,
      deleteSongs: songActions.deleteSongs,
      updateSong: songActions.updateSong,
      addSong: songActions.addSongDirect,
      showThumbnails: playbackState.showThumbnails,
      showAddedBy: settings.showAddedBy ?? false,
      queueSong: viewMode.queueSong,
      canEditRoom,
      isViewMode: viewMode.isViewMode,
      localPlayMode: false,
      onLocalPlay: viewMode.handleLocalPlay,
      localCurrentSongId: viewMode.localCurrentSongId,
    },
    settingsPanel: {
      room,
      showThumbnails: playbackState.showThumbnails,
      voteThreshold: playbackState.voteThreshold,
      voteMode: viewMode.voteMode,
      skipThreshold: playbackState.skipThreshold,
      allowSuggestions: settings.allowSuggestions ?? true,
      allowSuggestFromList: settings.allowSuggestFromList ?? false,
      tickerText: settings.tickerText ?? '',
      tickerOnScreen: settings.tickerOnScreen ?? false,
      tickerForGuests: settings.tickerForGuests ?? false,
      queueSize: Math.max(1, settings.queueSize ?? 1),
      saveSettings: commands.saveSettings,
      importPlaylist: playlistActions.importPlaylist,
      exportPlaylist: playlistActions.exportPlaylist,
      onRenameRoom: commands.renameRoom,
      onChangeRoomCode: commands.changeRoomCode,
      showQr: ui.panelOpen.qr,
      showQueueOverlay: ui.panelOpen.showQueue,
      showRoomCode: ui.panelOpen.showRoomCode,
      onToggleQr: () => ui.togglePanel('qr'),
      onToggleQueueOverlay: () => ui.togglePanel('showQueue'),
      onToggleShowRoomCode: () => ui.togglePanel('showRoomCode'),
      isVisible: settings.isVisible !== false,
      canEditRoom,
      onCopyRoomLink: shareLinks.copyVoterLink,
      roomLinkCopied: ui.uiState.copied === 'voter',
      onSubmitMessage: commands.submitContactMessage,
      partyDate: settings.partyDate ?? '',
      partyLocation: settings.partyLocation ?? '',
      partyDescription: settings.partyDescription ?? '',
      openParty: settings.openParty ?? false,
    },
    proposalsPanel: {
      room,
      suggestions,
      showThumbnails: playbackState.showThumbnails,
      removeVotingProposal: commands.removeVotingProposal,
      approveSuggestion: commands.approveSuggestion,
      approveAllSuggestions: commands.approveAllSuggestions,
      rejectSuggestion: commands.rejectSuggestion,
      rejectAllSuggestions: commands.rejectAllSuggestions,
      canEditRoom,
      onCreateRoomFromYt: commands.handleCreateRoomFromYt,
      onAddYtToRoom: commands.handleAddYtToRoom,
      ownedRooms,
      newSongUrl: ui.uiState.newSongUrl,
      handleSongUrlChange: ui.handleSongUrlChange,
      handleUrlBlur: songActions.handleUrlBlur,
      addSongByUrl: songActions.addSong,
      songSearchSuggestions: songActions.suggestions,
      selectSuggestion: songActions.selectSuggestion,
      clearSuggestions: songActions.clearSuggestions,
      newSongTitle: ui.uiState.newSongTitle,
      fetchingTitle: ui.uiState.fetchingTitle,
      urlErr: ui.uiState.urlErr,
    },
  }
}

export function buildOwnerScreenModel({
  room,
  canEditRoom,
  route,
  ownedRooms,
  settings,
  suggestions,
  shareLinks,
  ui,
  playback,
  playbackState,
  votingState,
  commands,
  playlistActions,
  songActions,
  handleLocalPlay,
}) {
  return {
    room,
    canEditRoom,
    ui: {
      leftPanel: ui.leftPanel,
      panelOpen: ui.panelOpen,
      togglePanel: ui.togglePanel,
      toggleLeftPanel: ui.toggleLeftPanel,
    },
    sidebar: buildOwnerSidebarModel({
      room,
      canEditRoom,
      settings,
      suggestions,
      ownedRooms,
      ui,
      playbackState,
      commands,
      playlistActions,
      songActions,
      shareLinks,
      viewMode: {
        isViewMode: route.isViewMode,
        playSongNow: playback.playSongNow,
        queueSong: playback.queueSong,
        handleLocalPlay,
        localCurrentSongId: ui.localCurrentSongId,
        voteMode: playback.voteMode,
      },
    }),
    playback: {
      isPlaying: playbackState.isPlaying,
      currentSong: playbackState.currentSong,
      remaining: playback.remaining,
      ytPlayerState: playback.ytPlayerState,
      loadProgress: playback.loadProgress,
      playerRef: playback.playerRef,
      playerDivRef: playback.playerDivRef,
      playerReady: playback.playerReady,
      advanceToWinner: playback.advanceToWinner,
      skipThreshold: playbackState.skipThreshold,
      skipCount: playbackState.skipCount,
      startJukebox: playback.startJukebox,
      stopJukebox: playback.stopJukebox,
      queue: playbackState.queue,
      removeFromQueue: playback.removeFromQueue,
    },
    voting: {
      voteMode: playback.voteMode,
      voteThreshold: playbackState.voteThreshold,
      nextOptionKeys: votingState.nextOptionKeys,
      nextOptions: votingState.nextOptions,
      nextVotesData: votingState.nextVotesData,
      playSongNow: playback.playSongNow,
      queueSong: playback.queueSong,
      replaceSong: playback.replaceSong,
      removeVotingOption: playback.removeVotingOption,
      advanceToOption: playback.advanceToOption,
    },
    sharing: {
      shareLinks,
      copied: ui.uiState.copied,
    },
    viewMode: {
      isViewMode: route.isViewMode,
      handleCopyRoom: commands.handleCopyRoom,
      copyingRoom: ui.copyingRoom,
      handleAppendToRoom: commands.handleAppendToRoom,
      appendingRoom: ui.appendingRoom,
      ownedRooms,
      localCurrentSongId: ui.localCurrentSongId,
      handleLocalPlay,
    },
  }
}

export function buildGuestScreenModel({
  auth,
  room,
  settings,
  playback,
  playbackState,
  votingState,
  commands,
  onOpenCookieSettings,
  isLoggedIn,
}) {
  return {
    isLoggedIn: isLoggedIn ?? false,
    isOwner: auth.isOwner,
    playerDivRef: playback.playerDivRef,
    isPlaying: playbackState.isPlaying,
    currentSong: playbackState.currentSong,
    remaining: playback.remaining,
    queue: playbackState.queue,
    nextOptionKeys: votingState.nextOptionKeys,
    nextOptions: votingState.nextOptions,
    nextVotesData: votingState.nextVotesData,
    userId: playbackState.userId,
    vote: commands.vote,
    skipThreshold: playbackState.skipThreshold,
    mySkipVote: playbackState.mySkipVote,
    voteSkip: commands.voteSkip,
    allowSuggestions: settings.allowSuggestions ?? true,
    allowSuggestFromList: settings.allowSuggestFromList ?? false,
    tickerText: settings.tickerText ?? '',
    tickerForGuests: settings.tickerForGuests ?? false,
    submitSuggestion: ((settings.allowSuggestions ?? false) && !(settings.requireSuggestionApproval ?? true))
      ? commands.submitSongToList
      : commands.submitSuggestion,
    submitVotingProposal: commands.submitVotingProposal,
    submitPlaylistSuggestion: commands.submitPlaylistSuggestion,
    myRating: playbackState.myRating,
    onRate: commands.rateActivePlaylist,
    showThumbnails: playbackState.showThumbnails,
    jukeboxState: room,
    onSubmitMessage: commands.submitContactMessage,
    onOpenCookieSettings,
  }
}

export function buildHomeScreen({
  auth,
  ownedRooms,
  upcomingOpenParties,
  topRatedRooms,
  commands,
  ui,
}) {
  return buildHomeScreenModel({
    auth,
    ownedRooms,
    upcomingOpenParties,
    topRatedRooms,
    commands,
    ui,
  })
}

export function buildRoomHeaderModel(input) {
  return buildHeaderModel(input)
}
